project:
  type: website
  output-dir: docs

website:
  title: "Long Term Intertidal Monitoring on Yellow Island" 
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: mentorship.qmd
        text: Mentorship
      - icon: github
        href: https://github.com/ChrisMantegna
      - icon: twitter
        href: https://twitter.com/SaffireSeahorse
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

# *A Black In Marine Science X The Nature Conservancy Program*"