---
title: "Long Term Intertidal Monitoring on Yellow Island."   
" *A Black In Marine Science x The Nature Conservancy Program* "
---

The impacts of anthropogenic activities on natural environments are growing ever more complex and far-reaching. Moreover, the impacts can be more pervasive and yet go unnoticed in aquatic habitats like marine intertidal environments. Long-term monitoring programs provide an opportunity to examine the (changing) relationship between organisms and their habitats to better inform our understanding of the interplay between biotic and abiotic conditions. This is the second year of the Yellow Island Monitoring project and the first full season of data collection. 

The Yellow Island project focus is on (1) understanding the island\'s ecology using observation, molecular techniques, and the synthesis of multi-source data, and (2) understanding the interconnectedness of the Salish Sea ecosystem and the foundational changes induced by human activities and climate change. Students will work both onsite at Yellow Island and in the lab collecting qualitative and quantitative data that can help us answer questions of intertidal community composition, food web dynamics, predator prey interactions, and physiological trade-offs in the face of a changing climate.
